version: '3'

services:
  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    command: './gradlew run'
    environment:
      _JAVA_OPTIONS: -Xms256m -Xmx512m
    ports:
      - '10100:8080' # to machine port : from container port
    working_dir: '/app'
    volumes:
      - '.:/app'
